"""
Unit tests for Idle RPG design content integration.

Covers:
- JSON data file generation (with and without a design doc)
- Flutter UI screens generated by the idle RPG genre plugin
- pubspec.yaml including assets/data/ entries
- Design-doc names populated in the generated JSON
"""

import json
import unittest

from game_generator.scaffolder import scaffold_project
from game_generator.spec import GameSpec


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _idle_spec(**kwargs) -> GameSpec:
    base: GameSpec = {
        "title": "Epic Idle",
        "genre": "idle_rpg",
        "mechanics": ["auto_battle", "level_up"],
        "required_assets": ["hero", "enemy"],
        "screens": ["game"],
        "controls": {"keyboard": ["click"], "mobile": ["tap"]},
        "progression": {"scoring": "experience", "levels": 20},
        "orientation": "portrait",
    }
    base.update(kwargs)
    return base


def _sample_design_doc() -> dict:
    return {
        "world": "A cursed kingdom shrouded in eternal twilight.",
        "premise": "Assemble heroes to banish the Shadow King.",
        "main_story_beats": ["The curse begins", "First hero rises", "Final battle"],
        "quests": [
            {
                "title": "Shadow Hunt",
                "summary": "Track the first shadow beast.",
                "giver": "Lady Seraphine",
                "level_range": [1, 5],
                "objectives": ["Defeat 3 shadow beasts"],
                "rewards": ["100 gold"],
            }
        ],
        "characters": [
            {
                "name": "Lady Seraphine",
                "role": "Guide",
                "backstory": "Ancient sorceress protecting the realm.",
                "motivations": ["Lift the curse"],
                "relationships": {},
            }
        ],
        "factions": [],
        "locations": [
            {
                "name": "Twilight Keep",
                "type": "castle",
                "description": "The Shadow King's fortress.",
                "notable_features": ["Throne room", "Dungeon"],
            }
        ],
        "items": [
            {
                "name": "Shadow Blade",
                "type": "weapon",
                "rarity": "rare",
                "description": "Forged from shadow essence.",
                "stats": {"attack": 25},
            }
        ],
        "enemies": [],
    }


# ---------------------------------------------------------------------------
# Tests: data files generated without design doc
# ---------------------------------------------------------------------------

class TestIdleRPGDefaultDataFiles(unittest.TestCase):
    """Idle RPG generates default JSON data files when no design doc is present."""

    def setUp(self):
        self.files = scaffold_project(_idle_spec())

    def test_quests_json_generated(self):
        self.assertIn("assets/data/quests.json", self.files)

    def test_characters_json_generated(self):
        self.assertIn("assets/data/characters.json", self.files)

    def test_items_json_generated(self):
        self.assertIn("assets/data/items.json", self.files)

    def test_locations_json_generated(self):
        self.assertIn("assets/data/locations.json", self.files)

    def test_quests_json_is_valid_json_list(self):
        data = json.loads(self.files["assets/data/quests.json"])
        self.assertIsInstance(data, list)
        self.assertGreater(len(data), 0)

    def test_characters_json_is_valid_json_list(self):
        data = json.loads(self.files["assets/data/characters.json"])
        self.assertIsInstance(data, list)
        self.assertGreater(len(data), 0)

    def test_quests_have_title_field(self):
        data = json.loads(self.files["assets/data/quests.json"])
        for quest in data:
            self.assertIn("title", quest)

    def test_characters_have_name_field(self):
        data = json.loads(self.files["assets/data/characters.json"])
        for char in data:
            self.assertIn("name", char)

    def test_items_have_name_and_type(self):
        data = json.loads(self.files["assets/data/items.json"])
        for item in data:
            self.assertIn("name", item)
            self.assertIn("type", item)


# ---------------------------------------------------------------------------
# Tests: data files generated WITH design doc
# ---------------------------------------------------------------------------

class TestIdleRPGDesignDocDataFiles(unittest.TestCase):
    """Idle RPG populates JSON data files from the design doc when available."""

    def setUp(self):
        spec = _idle_spec(design_doc_data=_sample_design_doc())
        self.files = scaffold_project(spec)

    def test_quests_json_uses_design_doc_data(self):
        data = json.loads(self.files["assets/data/quests.json"])
        titles = [q["title"] for q in data]
        self.assertIn("Shadow Hunt", titles)

    def test_quests_json_giver_from_design_doc(self):
        data = json.loads(self.files["assets/data/quests.json"])
        givers = [q.get("giver") for q in data]
        self.assertIn("Lady Seraphine", givers)

    def test_characters_json_uses_design_doc_data(self):
        data = json.loads(self.files["assets/data/characters.json"])
        names = [c["name"] for c in data]
        self.assertIn("Lady Seraphine", names)

    def test_items_json_uses_design_doc_data(self):
        data = json.loads(self.files["assets/data/items.json"])
        names = [i["name"] for i in data]
        self.assertIn("Shadow Blade", names)

    def test_locations_json_uses_design_doc_data(self):
        data = json.loads(self.files["assets/data/locations.json"])
        names = [l["name"] for l in data]
        self.assertIn("Twilight Keep", names)


# ---------------------------------------------------------------------------
# Tests: UI screen Dart files
# ---------------------------------------------------------------------------

class TestIdleRPGScreenFiles(unittest.TestCase):
    """Idle RPG generates Flutter UI screen files."""

    def setUp(self):
        self.files = scaffold_project(_idle_spec())

    def test_quest_log_screen_generated(self):
        self.assertIn("lib/screens/quest_log_screen.dart", self.files)

    def test_characters_screen_generated(self):
        self.assertIn("lib/screens/characters_screen.dart", self.files)

    def test_shop_screen_generated(self):
        self.assertIn("lib/screens/shop_screen.dart", self.files)

    def test_quest_log_screen_loads_json(self):
        dart = self.files["lib/screens/quest_log_screen.dart"]
        self.assertIn("assets/data/quests.json", dart)
        self.assertIn("rootBundle.loadString", dart)

    def test_characters_screen_loads_json(self):
        dart = self.files["lib/screens/characters_screen.dart"]
        self.assertIn("assets/data/characters.json", dart)
        self.assertIn("rootBundle.loadString", dart)

    def test_shop_screen_loads_json(self):
        dart = self.files["lib/screens/shop_screen.dart"]
        self.assertIn("assets/data/items.json", dart)
        self.assertIn("rootBundle.loadString", dart)

    def test_quest_log_screen_is_stateful_widget(self):
        dart = self.files["lib/screens/quest_log_screen.dart"]
        self.assertIn("StatefulWidget", dart)

    def test_characters_screen_is_stateful_widget(self):
        dart = self.files["lib/screens/characters_screen.dart"]
        self.assertIn("StatefulWidget", dart)

    def test_shop_screen_is_stateful_widget(self):
        dart = self.files["lib/screens/shop_screen.dart"]
        self.assertIn("StatefulWidget", dart)


# ---------------------------------------------------------------------------
# Tests: main.dart with navigation
# ---------------------------------------------------------------------------

class TestIdleRPGMainDart(unittest.TestCase):
    """Idle RPG generates a main.dart with bottom navigation."""

    def setUp(self):
        self.files = scaffold_project(_idle_spec())

    def test_main_dart_has_bottom_nav(self):
        main = self.files["lib/main.dart"]
        self.assertIn("BottomNavigationBar", main)

    def test_main_dart_imports_screens(self):
        main = self.files["lib/main.dart"]
        self.assertIn("quest_log_screen.dart", main)
        self.assertIn("characters_screen.dart", main)
        self.assertIn("shop_screen.dart", main)

    def test_main_dart_includes_game_widget(self):
        main = self.files["lib/main.dart"]
        self.assertIn("GameWidget", main)

    def test_main_dart_has_indexed_stack(self):
        main = self.files["lib/main.dart"]
        self.assertIn("IndexedStack", main)

    def test_main_dart_has_void_main(self):
        main = self.files["lib/main.dart"]
        self.assertIn("void main()", main)


# ---------------------------------------------------------------------------
# Tests: pubspec.yaml includes data assets
# ---------------------------------------------------------------------------

class TestIdleRPGPubspecAssets(unittest.TestCase):
    """pubspec.yaml must reference data JSON files."""

    def test_pubspec_includes_data_assets(self):
        files = scaffold_project(_idle_spec())
        pubspec = files["pubspec.yaml"]
        self.assertIn("assets/data/quests.json", pubspec)
        self.assertIn("assets/data/characters.json", pubspec)

    def test_pubspec_includes_imported_assets_dir(self):
        """assets/imported/ must always be in pubspec for game sprites."""
        files = scaffold_project(_idle_spec())
        pubspec = files["pubspec.yaml"]
        self.assertIn("assets/imported/", pubspec)

    def test_pubspec_includes_imported_and_data_when_both_present(self):
        paths = ["assets/imported/hero.png", "assets/imported/enemy.png"]
        files = scaffold_project(_idle_spec(), imported_asset_paths=paths)
        pubspec = files["pubspec.yaml"]
        for p in paths:
            self.assertIn(p, pubspec)
        self.assertIn("assets/data/quests.json", pubspec)

    def test_pubspec_includes_items_and_locations_when_generated(self):
        spec = _idle_spec(design_doc_data=_sample_design_doc())
        files = scaffold_project(spec)
        pubspec = files["pubspec.yaml"]
        self.assertIn("assets/data/items.json", pubspec)
        self.assertIn("assets/data/locations.json", pubspec)


if __name__ == "__main__":
    unittest.main()
