"""
scaffolder.py – Flutter/Flame project scaffolder.

Given a GameSpec and the genre-specific Dart files, produces a complete
dict of {relative_path: file_content} representing the full Flutter project.
"""

from __future__ import annotations

import os
from typing import Dict, List

from .spec import GameSpec
from .genres import get_genre_plugin

# Required files that every generated project must contain.
REQUIRED_FILES = {
    "pubspec.yaml",
    "lib/main.dart",
    "README.md",
    "ASSETS_LICENSE.md",
}


def scaffold_project(
    spec: GameSpec,
    imported_asset_paths: List[str] | None = None,
) -> Dict[str, str]:
    """
    Build a complete Flutter/Flame project file tree.

    Args:
        spec:                 GameSpec dict (from spec.generate_spec).
        imported_asset_paths: List of asset paths relative to the project root
                              that were copied from the user's assets folder,
                              e.g. ``["assets/imported/player.png", ...]``.

    Returns:
        dict mapping relative file path -> file content (str).
    """
    imported_asset_paths = imported_asset_paths or []

    files: Dict[str, str] = {}

    # 1. Genre-specific Dart game files
    plugin = get_genre_plugin(spec["genre"])
    files.update(plugin(spec))

    # Derive the main game class name from genre files
    game_class = _infer_game_class(spec)

    # 2. main.dart
    files["lib/main.dart"] = _main_dart(spec, game_class)

    # 3. pubspec.yaml
    files["pubspec.yaml"] = _pubspec_yaml(spec, imported_asset_paths)

    # 4. README.md
    files["README.md"] = _readme_md(spec)

    # 5. ASSETS_LICENSE.md
    files["ASSETS_LICENSE.md"] = _assets_license_md(spec)

    return files


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _infer_game_class(spec: GameSpec) -> str:
    """Derive the Flame game class name from the spec title."""
    title = spec.get("title", "MyGame")
    words = "".join(ch if ch.isalnum() or ch == " " else " " for ch in title).split()
    base = "".join(w.capitalize() for w in words) if words else "MyGame"
    return f"{base}Game"


def _main_dart(spec: GameSpec, game_class: str) -> str:
    title = spec.get("title", "My Game")
    return f"""\
import 'package:flame/game.dart';
import 'package:flutter/material.dart';
import 'game/game.dart';

void main() {{
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const {game_class}App());
}}

class {game_class}App extends StatelessWidget {{
  const {game_class}App({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: '{title}',
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: Colors.black,
        body: GameWidget<{game_class}>(
          game: {game_class}(),
          loadingBuilder: (context) => const Center(
            child: CircularProgressIndicator(),
          ),
        ),
      ),
    );
  }}
}}
"""


def _pubspec_yaml(spec: GameSpec, asset_paths: List[str]) -> str:
    title = spec.get("title", "my_game")
    # package name: lowercase, underscores
    pkg = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in title.lower()).strip("_")
    pkg = pkg or "my_game"

    asset_lines = ""
    if asset_paths:
        lines = "\n".join(f"    - {p}" for p in sorted(asset_paths))
        asset_lines = f"\n  assets:\n{lines}\n"
    else:
        asset_lines = "\n  assets:\n    - assets/imported/\n"

    return f"""\
name: {pkg}
description: A Flutter/Flame game generated by Aibase.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0

flutter:
  uses-material-design: true
{asset_lines}
"""


def _readme_md(spec: GameSpec) -> str:
    title = spec.get("title", "My Game")
    genre = spec.get("genre", "unknown")
    mechanics = ", ".join(spec.get("mechanics", []))
    controls = spec.get("controls", {})

    kb = ", ".join(controls.get("keyboard", []))
    mobile = ", ".join(controls.get("mobile", []))

    return f"""\
# {title}

Generated by **Aibase** – Flutter/Flame Game Generator.

## Genre
`{genre}`

## Mechanics
{mechanics}

## Controls
- **Keyboard / Desktop**: {kb}
- **Mobile**: {mobile}

## Prerequisites
- [Flutter SDK](https://docs.flutter.dev/get-started/install) ≥ 3.10
- Run `flutter pub get` before building.

## Getting Started
```bash
flutter pub get
flutter run
```

## Asset Licensing
See [ASSETS_LICENSE.md](ASSETS_LICENSE.md) for information about the assets
bundled with this project.
"""


def _assets_license_md(spec: GameSpec) -> str:
    title = spec.get("title", "My Game")
    return f"""\
# Asset Licensing – {title}

The assets located in `assets/imported/` were supplied by the user from a
local folder at project generation time.  **Aibase does not redistribute
these assets.**

## Your Responsibilities
- Ensure you hold the appropriate licence for every asset file included here.
- If assets originate from a third-party (e.g. itch.io asset packs), consult
  the relevant licence file (often `LICENSE.txt` or `README` inside the
  original pack) before distributing your game.
- Aibase does **not** automatically download assets from any online storefront;
  all assets in this project were explicitly provided by you.

## Placeholder Assets
If Aibase could not find a matching asset in your supplied folder it may have
generated a coloured rectangle placeholder in code.  Replace these with your
real artwork before publishing.
"""
